### ISSUE TITLE
Apostrophe imported incorrectly

### ISSUE THREAD

**Issue by mudnug** [julianpoy/RecipeClipper#75]
Clip https://recipes.heart.org/en/recipes/hoppin-john

Expected: 
Hoppin' John

Actual:
```Hoppin&#39; John```

**Comment by mudnug** [comment]
I'm not actually sure if this is an issue with Recipesage or with the clipper.

**Comment by mudnug** [comment]
Another example. Try to import https://www.food.com/recipe/bangkok-chicken-curry-476986 with RecipeSage
Expected:
"If you’ve ever wanted to make Thai food at home, you have to try this! It’s a great “impress your friends” dish."
Actual:
If you&rsquo;ve ever wanted to make Thai food at home, you have to try this!  It&rsquo;s a great &ldquo;impress your friends&rdquo; dish.

**Comment by julianpoy** [comment]
Not related to RecipeClipper

**Comment by julianpoy** [comment]
(I believe this should be solved in RecipeSage)

**Comment by mudnug** [comment]
I tried importing just now and still get the unexpected behavior. How do I determine if something is an issue with RecipeClipper vs RecipeSage? I thought these were with the former. Do youw ant them recreated against RecipeSage?

**Comment by julianpoy** [comment]
All issues should be opened against RecipeSage unless interacting directly with this package as a developer (it's available via NPM).

**Comment by mudnug** [comment]
Ok, that might be handy to add to somewhere to this repo so others know. (I thought you wanted the issues filed here if the bugs would likely need to be fixed here because they occurred across all platforms.)

**Comment by julianpoy** [comment]
No worries - This package is developer oriented. I'd just prefer to field import compat issues there, but I guess this is fine regardless. Will take a look at the issue and see if I can figure out what's going on.
